import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
const alice='10000000-0000-4000-8000-000000000001',bob='10000000-0000-4000-8000-000000000002',other='10000000-0000-4000-8000-000000000003';
test('真实 PostgreSQL：两人邀请、RLS、原子版本、幂等重试、删除与私密附件',async()=>{
  const db=new PGlite();
  try{
    await db.exec(`create role anon; create role authenticated; create schema auth;
      create table auth.users(id uuid primary key,email text,phone text,email_confirmed_at timestamptz,phone_confirmed_at timestamptz);
      create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
      grant usage on schema auth to anon,authenticated; grant execute on function auth.uid() to anon,authenticated;
      insert into auth.users values('${alice}','alice@example.test','8613812345678',now(),now()),('${bob}','bob@example.test','8613912345678',now(),now()),('${other}','other@example.test','8613712345678',now(),now());
      create schema storage;
      create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
      create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text,unique(bucket_id,name));
      alter table storage.objects enable row level security;
      grant usage on schema storage to anon,authenticated; grant all on storage.objects to anon,authenticated;`);
    await db.exec(await readFile(new URL('../supabase/migrations/202610100001_shared_journal.sql',import.meta.url),'utf8'));
    await db.exec(await readFile(new URL('../supabase/migrations/202610100002_private_attachments.sql',import.meta.url),'utf8'));
    const as=async(id,role='authenticated')=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id||'']);await db.exec(`set role ${role}`);};
    const rpc=async(name,args=[])=>{const placeholders=args.map((_,i)=>`$${i+1}`).join(',');return (await db.query(`select public.${name}(${placeholders}) as result`,args)).rows[0].result;};
    await as(null,'anon');await assert.rejects(()=>rpc('miao_create_household',['匿名']),/permission denied/);
    await as(alice);const household=await rpc('miao_create_household',['George']);assert(household);
    await assert.rejects(()=>rpc('miao_create_household',['第二份']),/已经加入/);
    const invitation=await rpc('miao_invite',[household,'phone','+86 13912345678']);assert.equal(invitation.token.length,64);
    await as(other);await assert.rejects(()=>rpc('miao_join',[invitation.token,'陌生人']),/被邀请/);
    assert.equal((await db.query('select * from public.miao_households')).rows.length,0);
    await assert.rejects(()=>rpc('miao_snapshot',[household]),/访问权限/);
    await assert.rejects(()=>db.query('select * from miao_private.invitations'),/permission denied/);
    await as(bob);assert.equal(await rpc('miao_join',[invitation.token,'小圆']),household);
    await assert.rejects(()=>rpc('miao_join',[invitation.token,'重试']),/无效|过期/);
    await as(alice);await assert.rejects(()=>rpc('miao_invite',[household,'email','other@example.test']),/已满/);
    const profile={id:crypto.randomUUID(),name:'测试猫',birthday:'2026-06-01',estimated:false,avatar:null};
    const apply=(kind,id,expected,value,operation=crypto.randomUUID())=>rpc('miao_apply',[household,operation,kind,id,expected,value]);
    assert.equal((await apply('profile','profile',0,profile)).status,'applied');
    assert.equal((await apply('budget','budget',0,50000)).status,'applied');
    assert.equal((await apply('budget','budget',1,null)).value,null);
    const expense=(id,cents)=>({id,type:'expense',at:'2026-10-10T12:00:00Z',day:'2026-10-10',updatedAt:'2026-10-10T12:00:00Z',cents,category:'食物',assets:[],title:'猫粮'});
    const record=expense('first',1999),operation=crypto.randomUUID();
    const first=await apply('record','first',0,record,operation);
    assert.equal(first.version,1);assert.equal((await apply('record','first',0,record,operation)).version,1);
    await assert.rejects(()=>apply('record','first',0,expense('first',3000),operation),/不匹配/);
    await as(bob);const conflict=await apply('record','first',0,expense('first',2000));assert.equal(conflict.status,'conflict');assert.equal(conflict.value.cents,1999);
    const updated=await apply('record','first',1,expense('first',2999));assert.equal(updated.createdBy,alice);assert.equal(updated.updatedBy,bob);
    await apply('record','second',0,expense('second',2000));
    await as(alice);const deleted=await apply('record','first',2,{...expense('first',2999),deletedAt:'2026-10-10T14:00:00Z'});assert(deleted.value.deletedAt);
    const stale=await apply('record','first',1,record);assert.equal(stale.status,'conflict');assert(stale.value.deletedAt);
    const snapshot=await rpc('miao_snapshot',[household]);assert.equal(snapshot.records.length,2);assert.equal(snapshot.members.length,2);
    assert.equal(snapshot.records.filter(r=>!r.value.deletedAt).reduce((sum,r)=>sum+r.value.cents,0),2000);
    await assert.rejects(()=>apply('profile','profile',1,{...profile,id:'different-cat'}),/另一只猫/);
    await assert.rejects(()=>apply('record','bad',0,{...expense('bad',10),assets:[{name:'a',mime:'image/jpeg',path:`other/anything`,data:'inline'}]}),/私密文件区/);
    await assert.rejects(()=>apply('record','bad-text',0,{...expense('bad-text',10),title:{nested:'object'}}),/文本格式/);
    await assert.rejects(()=>apply('record','bad-weight',0,{...expense('bad-weight',10),type:'weight',kg:-1}),/体重无效/);
    const file=`${household}/${alice}/hash`;
    await db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['miao-private',file]);
    await as(bob);assert.equal((await db.query('select * from storage.objects')).rows.length,1);
    await assert.rejects(()=>db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['miao-private',`${household}/${alice}/forged`]),/row-level security/);
    assert.equal((await db.query('update storage.objects set name=$1 returning *',['overwritten'])).rows.length,0);
    await as(other);assert.equal((await db.query('select * from storage.objects')).rows.length,0);
    await assert.rejects(()=>apply('record','evil',0,expense('evil',10)),/访问权限/);
    await as(null,'anon');assert.equal((await db.query('select * from storage.objects')).rows.length,0);
  }finally{await db.close();}
});
