import {publicAsset} from '../paths';
import {useState} from 'react';
import {Camera,Cat,ChevronRight,Plus,WandSparkles,Check,Bell,CalendarDays} from 'lucide-react';
import {Bowl,Empty,RecordList} from '../components/ui';
import {dayKey,expenseSummary,money} from '../model';
export function ExpenseBars({categories}) {const max=Math.max(1,...categories.map(c=>c.cents));return <div className="expense-bars">{categories.map((c,i)=><div className="expense-bar" key={c.name}><span>{c.name}</span><span className="bar-track"><span style={{width:`${c.cents/max*78}%`,opacity:1-i*.12}}/></span><span>{money(c.cents)}</span></div>)}</div>;}
export function Today({state,records,demo,onAdd,onProfile,onPage,onSelect,onComplete}) {
  const profile=state.profile;const latestWeight=records.find(r=>r.type==='weight');const latestFeed=records.find(r=>r.type==='feed');const summary=expenseSummary(records,dayKey().slice(0,7));const days=Math.max(1,Math.floor((Date.parse(`${dayKey()}T12:00:00`)-Date.parse(`${profile.birthday}T12:00:00`))/86400000)+1);
  const reminders=records.filter(r=>r.due&&!r.completedAt).sort((a,b)=>a.due.localeCompare(b.due));
  return <>
    <section className="profile-card" aria-label="猫咪档案"><div className="profile-avatar">{profile.avatar?<img src={profile.avatar.data} alt={`${profile.name}的头像`}/>:demo?<img src={publicAsset('demo-cat.jpg')} alt="示例猫小橘"/>:<Cat size={50} strokeWidth={1.3}/>}</div><div className="profile-information"><div className="profile-name-row"><div><h2>{profile.name}</h2><p>{profile.estimated?'估计':'出生'}第{days}天</p></div><button className="outline-button" onClick={onProfile}>{demo?'建立我的猫咪档案':'编辑档案'}</button></div><div className="profile-stats"><div><span>最新体重</span><strong>{latestWeight?`${latestWeight.kg} kg`:'未记录'}</strong></div><div><span>上次测量</span><strong>{latestWeight?`${Number(latestWeight.day.slice(5,7))}月${Number(latestWeight.day.slice(8))}日`:'未记录'}</strong></div></div></div></section>
    <section className="care-section"><h2>今天的照顾</h2><div className="quick-actions"><button onClick={()=>onAdd('feed')}><Bowl size={29}/><span>喂食</span></button><button onClick={()=>onAdd('behavior')}><WandSparkles size={29}/><span>玩耍</span></button><button onClick={()=>onAdd('journal')}><Camera size={29}/><span>日常</span></button></div><button className="last-feed" onClick={()=>latestFeed?onSelect(latestFeed):onAdd('feed')}><Bowl size={29}/><span><strong>{latestFeed?`上次记录喂食 ${latestFeed.day===dayKey()?new Date(latestFeed.at).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false}):`${Number(latestFeed.day.slice(5,7))}月${Number(latestFeed.day.slice(8))}日`} · ${latestFeed.food}${latestFeed.grams?` ${latestFeed.grams}g`:''}`:'还没有喂食记录'}</strong><small>记录观察，不代表实际摄入量</small></span></button></section>
    {reminders.length>0&&<section className="reminders-card"><div className="section-heading"><h2>照护提醒</h2><button className="text-button" onClick={()=>onPage('health')}>查看全部<ChevronRight size={17}/></button></div>{reminders.slice(0,2).map(r=><div className="reminder-row" key={r.id}><Bell size={18}/><span><strong>{r.title||r.kind}</strong><small className={r.due<dayKey()?'overdue':''}>{r.due<dayKey()?'已到期 · ':''}{r.due}</small></span><button className="icon-button" aria-label={`完成提醒 ${r.title||r.kind}`} onClick={()=>onComplete(r)}><Check size={20}/></button></div>)}</section>}
    <section className="expense-card"><div className="section-heading"><h2>本月花费</h2><button className="text-button" onClick={()=>onPage('expenses')}>查看明细<ChevronRight size={18}/></button></div><strong className="money-total">{money(summary.total)}</strong>{summary.categories.length?<ExpenseBars categories={summary.categories.slice(0,3)}/>:<p className="quiet">本月尚未记录花费</p>}</section>
    <section><div className="section-heading"><h2>最近的记录</h2></div>{records.some(r=>r.type!=='expense'&&r.type!=='reminder')?<RecordList records={records.filter(r=>r.type!=='expense'&&r.type!=='reminder')} limit={3} onSelect={onSelect}/>:<Empty title="故事从今天开始" text="喂食、拍照，或记下一个小变化。"/>}</section>
  </>;
}
function WeightChart({records}) {
  const points=records.filter(r=>r.type==='weight').slice(0,12).reverse();if(!points.length)return <Empty title="还没有体重记录" text="记录真实测量值，慢慢看见成长曲线。"/>;
  const min=Math.min(...points.map(r=>r.kg))*.93;const max=Math.max(...points.map(r=>r.kg))*1.07;const w=340,h=128;const start=Date.parse(points[0].at),end=Date.parse(points.at(-1).at);const x=r=>24+(end===start?146:(Date.parse(r.at)-start)/(end-start)*292);const y=r=>105-(r.kg-min)/(max-min)*80;const coords=points.map((r,i)=>`${x(r,i)},${y(r)}`).join(' ');
  return <div className="weight-chart"><div className="chart-value"><strong>{points.at(-1).kg}<span> kg</span></strong><small>最近一次 · {points.at(-1).day}</small></div><svg viewBox={`0 0 ${w} ${h}`} role="img" aria-label={`体重记录：${points.map(r=>`${r.day} ${r.kg}千克`).join('，')}`}><path d="M24 25H316M24 65H316M24 105H316" stroke="#e9e1d9" strokeDasharray="3 4" fill="none"/>{points.length>1&&<polyline points={coords} stroke="#c56c32" strokeWidth="2.5" fill="none"/>}{points.map((r,i)=><circle key={r.id} cx={x(r,i)} cy={y(r)} r="4" fill="#c56c32"/>)}<text x="24" y="126" fontSize="11" fill="#8c8379">{points[0].day.slice(5)}</text><text x="316" y="126" textAnchor="end" fontSize="11" fill="#8c8379">{points.at(-1).day.slice(5)}</text></svg><p className="form-hint">显示最近 12 次真实测量，横轴按日期间隔排列。</p></div>;
}
export function Growth({records,onAdd,onSelect}) {
  const [filter,setFilter]=useState('全部');const list=records.filter(r=>r.type!=='expense'&&r.type!=='reminder').filter(r=>filter==='全部'||(filter==='成长'&&r.type==='weight')||(filter==='饮食'&&r.type==='feed')||(filter==='日常'&&r.type==='journal'));
  return <><section className="white-panel"><div className="section-heading"><h2>体重趋势</h2><button className="text-button" onClick={()=>onAdd('weight')}><Plus size={17}/>记体重</button></div><WeightChart records={records}/></section><section><div className="section-heading"><h2>成长时间线</h2><button className="text-button" onClick={()=>onAdd('journal')}><Camera size={17}/>记日常</button></div><div className="filter-tabs" aria-label="记录分类">{['全部','成长','饮食','日常'].map(f=><button key={f} className={filter===f?'active':''} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}</div>{list.length?<RecordList records={list} onSelect={onSelect}/>:<Empty/>}</section></>;
}
export function Health({records,onAdd,onSelect,onComplete,onCalendar}) {
  const [section,setSection]=useState('健康档案');const health=records.filter(r=>r.type==='health');const behavior=records.filter(r=>r.type==='behavior');const reminders=records.filter(r=>r.due).sort((a,b)=>Boolean(a.completedAt)-Boolean(b.completedAt)||a.due.localeCompare(b.due));
  return <><div className="segmented-tabs" aria-label="健康与行为分区">{['健康档案','行为观察'].map(s=><button key={s} className={section===s?'active':''} onClick={()=>setSection(s)} aria-pressed={section===s}>{s}</button>)}</div>{section==='健康档案'?<><section className="white-panel"><div className="section-heading"><h2>照护提醒</h2><button className="text-button" onClick={()=>onAdd('reminder')}><Plus size={17}/>添加</button></div>{reminders.length?<><div className="reminders">{reminders.map(r=><div className={`reminder-row ${r.completedAt?'completed':''}`} key={r.id}><CalendarDays size={20}/><button className="reminder-copy" onClick={()=>onSelect(r)}><strong>{r.title||r.kind}</strong><small className={!r.completedAt&&r.due<dayKey()?'overdue':''}>{r.completedAt?'已完成 · ':r.due<dayKey()?'已到期 · ':''}{r.due}</small></button><button className="icon-button" aria-label={r.completedAt?`重新开启提醒 ${r.title||r.kind}`:`完成提醒 ${r.title||r.kind}`} onClick={()=>onComplete(r)}><Check size={21}/></button></div>)}</div><button className="secondary-button" onClick={onCalendar}>导出到手机日历</button></>:<p className="quiet">暂无提醒，可按已确认的照护计划添加。</p>}</section><section><div className="section-heading"><h2>健康记录</h2><button className="text-button" onClick={()=>onAdd('health')}><Plus size={17}/>添加</button></div>{health.length?<RecordList records={health} onSelect={onSelect}/>:<Empty title="健康资料，放在一起" text="记录疫苗、驱虫、就诊和报告，回顾更方便。"/>}</section></>:<><div className="observation-intro"><WandSparkles size={27}/><h2>留意它的小变化</h2><p>玩耍、互动、躲藏，以及当时的环境。<br/>留下一次观察，方便与平时对照。</p><button className="primary-button" onClick={()=>onAdd('behavior')}>添加行为观察</button></div>{behavior.length?<RecordList records={behavior} onSelect={onSelect}/>:<Empty title="还没有行为观察" text="没有记录的日子，不代表状态正常。"/>}</>}</>;
}
export function Expenses({state,records,onAdd,onSelect,onBudget}) {
  const [month,setMonth]=useState(dayKey().slice(0,7));const summary=expenseSummary(records,month);const coverage=new Set(summary.entries.map(r=>r.day)).size;
  return <><div className="month-selector"><label htmlFor="expense-month">查看月份</label><input id="expense-month" type="month" value={month} onChange={e=>setMonth(e.target.value||dayKey().slice(0,7))}/></div><section className="expense-card"><div className="section-heading"><h2>已记花费</h2><button className="text-button" onClick={onBudget}>{state.budgetCents?'修改预算':'设置预算'}<ChevronRight size={17}/></button></div><strong className="money-total large">{money(summary.total)}</strong><p className="quiet">{summary.entries.length} 笔 · {coverage} 天有消费记录</p>{state.budgetCents&&<div className="budget"><div><span>月预算 {money(state.budgetCents)}</span><strong>{summary.total>state.budgetCents?'超出':'剩余'} {money(Math.abs(state.budgetCents-summary.total))}</strong></div><div className="bar-track"><span style={{width:`${Math.min(100,summary.total/state.budgetCents*100)}%`}}/></div></div>}{summary.categories.length>0&&<ExpenseBars categories={summary.categories}/>}</section><section><div className="section-heading"><h2>花费明细</h2><button className="text-button" onClick={()=>onAdd('expense')}><Plus size={17}/>记一笔</button></div>{summary.entries.length?<RecordList records={summary.entries} onSelect={onSelect}/>:<Empty title="这个月还没有记账" text="按实付金额记录，分类看清钱花在哪里。" action={<button className="secondary-button" onClick={()=>onAdd('expense')}>记录第一笔花费</button>}/>}<p className="footnote">按付款日期统计。未记录的消费不会计入汇总。</p></section></>;
}
