import {useState} from 'react';
import {Download,Upload,ChevronRight,Pencil,Smartphone,ShieldCheck} from 'lucide-react';
import {Field} from '../components/ui';
import {toCents} from '../model';
export function Settings({state,demo,onProfile,onExport,onImport}) {
  const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  async function importFile(e){const file=e.target.files[0];e.target.value='';if(!file)return;setError('');setBusy(true);try{const value=JSON.parse(await file.text());onImport(value);}catch(err){setError(err.message==='Unexpected end of JSON input'?'备份文件不完整':err.message);}finally{setBusy(false);}}
  return <div className="settings-content"><div className="settings-group"><button className="settings-row" onClick={onProfile}><Pencil size={21}/><span><strong>{demo?'建立我的猫咪档案':'编辑猫咪档案'}</strong><small>{demo?'从空白开始记录':state.profile.name}</small></span><ChevronRight size={18}/></button></div><div className="settings-group"><h3>备份与恢复</h3><p className="form-hint">记录保存在当前设备。换手机或清理浏览器前，请导出包含照片和资料的完整备份。</p><button className="settings-row" onClick={onExport} disabled={demo}><Download size={22}/><span><strong>导出完整备份</strong><small>{state.lastBackupAt?`上次导出 ${new Date(state.lastBackupAt).toLocaleDateString('zh-CN')}`:'尚未导出'}</small></span><ChevronRight size={18}/></button><label className={`settings-row ${busy?'disabled':''}`}><Upload size={22}/><span><strong>{busy?'读取中…':'导入备份'}</strong><small>先预览，再合并；相同记录不重复添加</small></span><ChevronRight size={18}/><input className="visually-hidden" aria-label="导入备份文件" type="file" accept=".json,.miao,application/json" onChange={importFile} disabled={busy}/></label>{error&&<p className="form-error" role="alert">{error}</p>}</div><div className="settings-group"><h3><Smartphone size={19}/>放到手机桌面</h3><p>iPhone：用 Safari 打开网址，点分享，再选择“添加到主屏幕”。</p><p>Android：在浏览器菜单中选择“安装应用”或“添加到主屏幕”。</p><p className="form-hint">建议先添加到主屏幕，再从桌面打开并建档。首次联网打开后支持离线记录。提醒可导出到手机日历。</p></div><p className="privacy-note"><ShieldCheck size={17}/>猫咪记录与照片保存在本机，没有云同步。</p></div>;
}
export function BudgetForm({budgetCents,onSave,onClose}) {
  const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  async function submit(e){e.preventDefault();setBusy(true);try{const raw=String(new FormData(e.currentTarget).get('budget')||'').trim();await onSave(raw?toCents(raw):null);onClose();}catch(err){setError(err.message);}finally{setBusy(false);}}
  return <form className="record-form" onSubmit={submit}><Field label="每月预算（元，可选）" hint="留空可取消预算。它不会改变已记录的花费。"><input name="budget" type="number" min="0.01" max="1000000" step="0.01" inputMode="decimal" defaultValue={budgetCents?budgetCents/100:''} placeholder="例如：500"/></Field>{error&&<p role="alert" className="form-error">{error}</p>}<button className="primary-button" disabled={busy}>保存预算</button></form>;
}
