import {useEffect,useRef,useState} from 'react';
import {Settings as SettingsIcon,House,BookOpen,Heart,Wallet,Plus,Weight,Camera,WandSparkles,Stethoscope,Bell,Pencil,Trash2,WifiOff,Check,Download} from 'lucide-react';
import {publicAsset} from './paths';
import {useJournal} from './useJournal';
import {LABELS,calendarFile,dayKey,makeDemo,mergeBackup,recordDescription,validateBackup,visibleRecords} from './model';
import {download} from './storage';
import {Assets,Bowl,Sheet,TYPE_ICONS} from './components/ui';
import {Today,Growth,Health,Expenses} from './features/Screens';
import RecordForm from './features/RecordForm';
import ProfileForm from './features/ProfileForm';
import {Settings,BudgetForm} from './features/Settings';
import Sharing,{SyncBanner} from './features/Sharing';
import {useCloudAccount} from './cloud/useCloudAccount';
const pages=[{id:'today',label:'今天',Icon:House},{id:'growth',label:'成长',Icon:BookOpen},{id:'health',label:'健康',Icon:Heart},{id:'expenses',label:'花费',Icon:Wallet}];
const addOptions=[['feed',Bowl,'喂食','食物、投喂量与食欲'],['weight',Weight,'体重','记录一次真实测量'],['health',Stethoscope,'健康','疫苗、就诊与健康资料'],['behavior',WandSparkles,'行为观察','玩耍、互动与环境变化'],['journal',Camera,'日常','照片与值得记住的小事'],['expense',Wallet,'花费','实付金额与分类'],['reminder',Bell,'提醒','已确认的照护计划']];
export default function App() {
  const cloud=useCloudAccount();const {state,ready,error,saving,commit,sync,syncNow,resolveConflict}=useJournal(cloud);const [page,setPage]=useState('today');const [modal,setModal]=useState(null);const [toast,setToast]=useState(null);const [offline,setOffline]=useState(!navigator.onLine);const [swReady,setSwReady]=useState(false);const toastTimer=useRef(null);const pendingType=useRef(null);
  const demo=!state.profile;const display=demo?makeDemo():state;const records=visibleRecords(display);
  useEffect(()=>{const update=()=>setOffline(!navigator.onLine);window.addEventListener('online',update);window.addEventListener('offline',update);if('serviceWorker'in navigator&&import.meta.env.PROD)navigator.serviceWorker.register(publicAsset('sw.js'),{scope:import.meta.env.BASE_URL}).then(()=>navigator.serviceWorker.ready).then(()=>setSwReady(true)).catch(()=>setSwReady(false));return()=>{window.removeEventListener('online',update);window.removeEventListener('offline',update);clearTimeout(toastTimer.current);};},[]);
  useEffect(()=>{if(new URLSearchParams(location.hash.slice(1)).has('join'))setModal({kind:'sharing'});},[]);
  function notify(message,action){clearTimeout(toastTimer.current);setToast({message,action});toastTimer.current=setTimeout(()=>setToast(null),action?9000:4500);}
  function go(next){setPage(next);window.scrollTo({top:0,behavior:'instant'});}
  function openAdd(type){if(demo){pendingType.current=type;setModal({kind:'profile'});}else setModal({kind:'record',type});}
  function closeProfile(){const type=pendingType.current;pendingType.current=null;setModal(type?{kind:'record',type}:null);}
  async function saveRecord(record){await commit(s=>({...s,records:[...s.records.filter(r=>r.id!==record.id),record]}));notify('记录已保存在本机');}
  async function saveProfile(profile){await commit(s=>({...s,profile}));go('today');notify('猫咪档案已保存');}
  async function deleteRecord(record){try{const deletedAt=new Date().toISOString();await commit(s=>({...s,records:s.records.map(r=>r.id===record.id?{...r,deletedAt,updatedAt:deletedAt}:r)}));setModal(null);notify('记录已移除',{label:'撤销',run:async()=>{try{await commit(s=>({...s,records:s.records.map(r=>r.id===record.id?{...r,deletedAt:null,updatedAt:new Date().toISOString()}:r)}));notify('记录已恢复');}catch(e){notify(e.message);}}});}catch(e){notify(e.message);}}
  async function complete(record){if(demo)return openAdd('reminder');try{await commit(s=>({...s,records:s.records.map(r=>r.id===record.id?{...r,completedAt:r.completedAt?null:new Date().toISOString(),updatedAt:new Date().toISOString()}:r)}));notify(record.completedAt?'提醒已重新开启':'已标记完成');}catch(e){notify(e.message);}}
  async function exportBackup(){if(demo)return;try{const lastBackupAt=new Date().toISOString();const next=await commit(s=>({...s,lastBackupAt}));download(JSON.stringify({format:'miao-growth-backup',version:1,exportedAt:lastBackupAt,state:next}),`喵成长-${state.profile.name}-${dayKey()}.miao.json`);notify('备份已导出，请保存到文件或云盘');}catch(e){notify(e.message);}}
  function previewImport(value){const incoming=validateBackup(value);mergeBackup(state,incoming);setModal({kind:'import',incoming});}
  async function restore(){try{await commit(s=>mergeBackup(s,modal.incoming));setModal(null);go('today');notify('备份已合并，相同记录不会重复添加');}catch(e){notify(e.message);}}
  function exportCalendar(){const due=records.filter(r=>r.due&&!r.completedAt);if(!due.length)return notify('没有待完成的提醒');download(calendarFile(due),'喵成长-照护提醒.ics','text/calendar');notify('日历文件已导出，请在手机日历中打开');}
  if(!ready)return <main className="loading"><img src={publicAsset('icon.svg')} alt=""/><p>打开成长记录本…</p></main>;
  if(error)return <main className="loading"><h1>暂时无法读取记录</h1><p role="alert">{error}</p><p>请保留浏览器原数据，检查存储设置后重试。</p><button className="primary-button" onClick={()=>location.reload()}>重新打开</button></main>;
  const titles={today:`${display.profile.name}的今天`,growth:'成长日记',health:'健康与行为',expenses:'每月花费'};
  const subtitles={today:new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'}).replace('日','日 · '),growth:'把每个小变化，留在时间里',health:'照护资料与日常观察，随时回顾',expenses:'一笔一笔，照顾好它的小生活'};
  return <div className="app-shell"><header className="app-header"><div><h1>{titles[page]}</h1><p>{subtitles[page]}</p></div><button className="settings-button" aria-label="设置与备份" onClick={()=>setModal({kind:'settings'})}><SettingsIcon size={24}/><span>{demo?'示例预览':'设置'}</span></button></header><SyncBanner cloud={cloud} sync={sync} offline={offline} onOpen={()=>setModal({kind:'sharing'})}/>{offline&&<div className="offline-note" role="status"><WifiOff size={15}/>{swReady?'当前离线，记录仍可保存在本机':'当前离线，已打开的页面仍可记录'}</div>}
    <main className="page-content">{page==='today'&&<Today state={display} records={records} demo={demo} onAdd={openAdd} onProfile={()=>setModal({kind:'profile'})} onPage={go} onSelect={record=>setModal({kind:'detail',record})} onComplete={complete}/>} {page==='growth'&&<Growth records={records} onAdd={openAdd} onSelect={record=>setModal({kind:'detail',record})}/>} {page==='health'&&<Health records={records} onAdd={openAdd} onSelect={record=>setModal({kind:'detail',record})} onComplete={complete} onCalendar={exportCalendar}/>} {page==='expenses'&&<Expenses state={display} records={records} onAdd={openAdd} onSelect={record=>setModal({kind:'detail',record})} onBudget={()=>demo?openAdd('expense'):setModal({kind:'budget',version:state._budgetVersion})}/>}</main>
    <button className="floating-add" aria-label="新增记录" onClick={()=>setModal({kind:'choose'})}><Plus size={29}/></button><nav className="bottom-nav" aria-label="主要导航">{pages.map(({id,label,Icon})=><button key={id} className={page===id?'selected':''} aria-current={page===id?'page':undefined} onClick={()=>go(id)}><Icon size={24} strokeWidth={1.7}/><span>{label}</span></button>)}</nav>
    {toast&&<div className="toast" role="status"><span>{toast.message}</span>{toast.action&&<button onClick={toast.action.run}>{toast.action.label}</button>}</div>}
    {modal?.kind==='choose'&&<Sheet title="记下一件小事" onClose={()=>setModal(null)}><div className="add-options">{addOptions.map(([type,Icon,label,subtitle])=><button key={type} onClick={()=>openAdd(type)}><span className="option-icon"><Icon size={24}/></span><span><strong>{label}</strong><small>{subtitle}</small></span><Plus size={18}/></button>)}</div></Sheet>}
    {modal?.kind==='profile'&&<Sheet title={demo?'建立猫咪档案':'编辑猫咪档案'} onClose={()=>{pendingType.current=null;setModal(null);}}><ProfileForm profile={state.profile} onSave={saveProfile} onClose={closeProfile}/></Sheet>}
    {modal?.kind==='record'&&<Sheet title={`${modal.record?'编辑':'记录'}${LABELS[modal.type]}`} onClose={()=>setModal(null)}><RecordForm key={modal.record?.id||modal.type} type={modal.type} record={modal.record} latestFeed={records.find(r=>r.type==='feed')} healthRecords={records.filter(r=>r.type==='health')} onSave={saveRecord} onClose={()=>setModal(null)}/></Sheet>}
    {modal?.kind==='detail'&&<Sheet title={modal.record.title||modal.record.kind||LABELS[modal.record.type]} onClose={()=>setModal(null)}><RecordDetail record={modal.record} demo={demo} onEdit={()=>demo?openAdd(modal.record.type):setModal({kind:'record',type:modal.record.type,record:modal.record})} onDelete={()=>deleteRecord(modal.record)} saving={saving}/></Sheet>}
    {modal?.kind==='settings'&&<Sheet title="设置与备份" onClose={()=>setModal(null)}><Settings state={display} demo={demo} shared={Boolean(sync)} onSharing={()=>setModal({kind:'sharing'})} onProfile={()=>setModal({kind:'profile'})} onExport={exportBackup} onImport={previewImport}/></Sheet>}
    {modal?.kind==='sharing'&&<Sheet title="共同记录" onClose={()=>setModal(null)}><Sharing cloud={cloud} sync={sync} state={state} onSync={syncNow} onResolve={resolveConflict}/></Sheet>}
    {modal?.kind==='budget'&&<Sheet title="每月预算" onClose={()=>setModal(null)}><BudgetForm budgetCents={state.budgetCents} onSave={budgetCents=>commit(s=>({...s,budgetCents,_budgetVersion:modal.version}))} onClose={()=>setModal(null)}/></Sheet>}
    {modal?.kind==='import'&&<Sheet title="确认恢复备份" onClose={()=>setModal(null)}><div className="restore-preview"><Download size={36}/><h3>{modal.incoming.profile.name}的记录</h3><p>{modal.incoming.records.filter(r=>!r.deletedAt).length} 条记录 · {modal.incoming.records.reduce((sum,r)=>sum+r.assets.length,0)} 个附件</p><p className="form-hint">合并到当前设备。相同记录按更新时间合并，重复导入不会重复计费。</p><button className="primary-button" disabled={saving} onClick={restore}>{saving?'恢复中…':'确认恢复'}</button><button className="secondary-button" onClick={()=>setModal(null)}>取消</button></div></Sheet>}
  </div>;
}
function RecordDetail({record,demo,onEdit,onDelete,saving}) {const Icon=TYPE_ICONS[record.type]||Camera;return <div className="record-detail"><div className="detail-summary"><span className="record-icon"><Icon size={25}/></span><div><p>{recordDescription(record)}</p><small>{new Date(record.at).toLocaleString('zh-CN',{hour12:false})}</small></div></div>{record.note&&record.type!=='behavior'&&record.type!=='weight'&&record.type!=='expense'&&<p className="detail-note">{record.note}</p>}{record.due&&<p className="detail-note">下次日期：{record.due}{record.completedAt?' · 已完成':''}</p>}{record.linkedHealthId&&<p className="form-hint">已关联健康事件，费用仅统计一次。</p>}<Assets assets={record.assets}/>{demo&&<p className="form-hint">这是示例记录，建立档案后开始自己的记录。</p>}<div className="detail-actions"><button className="secondary-button" onClick={onEdit}><Pencil size={18}/>{demo?'建立档案':'编辑记录'}</button>{!demo&&<button className="danger-button" disabled={saving} onClick={onDelete}><Trash2 size={18}/>移除记录</button>}</div></div>;}
